name: intune
description: A new Flutter plugin project.
version: 0.1.0
homepage: https://github.com/predatorx7/intune.git

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intune_platform_interface: ^0.1.0
  meta: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    # implements: intune
    platforms:
      android:
        package: com.hdfc.flutter_plugins.intune_android
        pluginClass: IntuneAndroidPlugin
      ios:
        pluginClass: IntuneIosPlugin
